spring.application.name=food-delivery
spring.datasource.url=jdbc:mysql://localhost:3306/food_delivery
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt_issuer=foody_delivery_app
jwt_secret_key=18OFEcVdXKQOAx2Scc3VmEbjVnt/Qt+x9XQzDNDMUYY=